server:
  port: 0
  servlet: 
    context-path: /post
  
spring:
  application:
    name: mspost
  jackson:
    serialization:
      indent-output: true
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:7703/ms_post?createDatabaseIfNotExist=true&characterEncoding=UTF-8&autoReconnect=true&useSLL=false&useLegacyDatetimeCode=false
    username: administrator
    password: mariadbDocker
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        '[format_sql]': true

  zipkin:
    base-url: http://localhost:9411
    sender.type: web
    sleuth.sampler.probability: 1


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 6
    registry-fetch-interval-seconds: 5

