server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: msuser
          uri: lb://msuser
          predicates:
            - Path=/user/**
        - id: mspost
          # lb = load balancer
          uri: lb://mspost
          predicates:
            - Path=/post/**
        - id: mscomment
          uri: lb://mscomment
          predicates:
            - Path=/comment/**
        - id: msrating
          uri: lb://msrating
          predicates:
            - Path=/rating/**
        - id: msbackup
          uri: lb://msbackup
          predicates:
            - Path=/backup/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
        web:
          server: trace
